apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo
  labels:
    app: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: 230273005112.dkr.ecr.eu-central-1.amazonaws.com/to-do-app:298dec2
        ports:
        - containerPort: 80
          name: web
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 60
          periodSeconds: 3