apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
  labels:
    app: todo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-089be4069e5d73aab"
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: web