apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
  labels:
    app: todo
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: web